services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GRADLE_USER_HOME=/tmp/gradle-cache
    volumes:
      - /tmp/gradle-cache:/tmp/gradle-cache
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: netology
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  mysql-data: