spring.application.name: cloud-service

spring.profiles.include: prod, test
spring.profiles.active: prod
spring.jpa.show-sql: true
spring.jackson.serialization.fail-on-empty-beans: false

management.endpoints.web.exposure.include: health
management.endpoint.health.show-details: always
management.endpoint.health.probes.enabled: true
management.health.db.enabled: true

#remove in final commit
spring.mvc.log-request-details: true
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
    org:
      springframework: DEBUG
      hibernate: DEBUG