spring:
  application:
    name: cloud-service
  profiles:
    active: prod
  jackson:
    serialization:
      fail-on-empty-beans: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
        filter:
          CommonsRequestLoggingFilter: DEBUG
        servlet:
          DispatcherServlet: DEBUG
      apache:
        catalina:
          filters:
            RequestDumperFilter: DEBUG
      #hibernate:
        #SQL: DEBUG
  config: classpath:log4j2.xml