spring:
  application:
    name: cloud-service
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/netology
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
