spring:
  application:
    name: cloud-service
  profiles:
    active: prod
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: true

logging:
  level:
    org.springframework: WARN
    org.apache.catalina: WARN
    org.hibernate: ERROR
    org.springframework.security: INFO
    io.restassured: INFO
  config: classpath:log4j2.xml