spring:
  application:
    name: cloud-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/netology
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


  mvc:
    log-request-details: true
logging:
  level:
    org.springframework.security: TRACE
    org.hibernate: DEBUG
    com.zaxxer.hikari: DEBUG
