spring:
  application:
    name: cloud-service
  profiles:
    active: prod
  jackson:
    serialization:
      fail-on-empty-beans: false
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes.enabled: true
  health:
    db:
      enabled: true